import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DynamicContextProvider, FilterChain } from "@dynamic-labs/sdk-react-core";
import { StarknetWalletConnectors } from "@dynamic-labs/starknet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    
    <html lang="en">
      <DynamicContextProvider
    settings={{
      environmentId: 'a4222566-9074-49f4-abdc-cf54606b96ab',
        walletConnectors: [ StarknetWalletConnectors ],
      }}
    >
      <body className={inter.className}>{children}</body>
    </DynamicContextProvider>
    </html>
  );
}
